import '../models/flight.dart';

class FlightService {
  static const Map<String, Flight> _flightDatabase = {
    'MS001': Flight(
      flightNumber: 'MS001',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'London Heathrow',
      destinationCode: 'LHR',
      departureTime: '08:30',
      arrivalTime: '12:45',
      status: 'On Time',
      gate: 'B14',
      terminal: 'Terminal 2',
      aircraft: 'Boeing 777-300ER',
      duration: '5h 15m',
      date: 'Apr 27, 2026',
      statusColor: 'green',
    ),
    'MS002': Flight(
      flightNumber: 'MS002',
      origin: 'London Heathrow',
      originCode: 'LHR',
      destination: 'Cairo',
      destinationCode: 'CAI',
      departureTime: '14:20',
      arrivalTime: '20:35',
      status: 'On Time',
      gate: 'A7',
      terminal: 'Terminal 4',
      aircraft: 'Boeing 777-300ER',
      duration: '5h 15m',
      date: 'Apr 27, 2026',
      statusColor: 'green',
    ),
    'MS100': Flight(
      flightNumber: 'MS100',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'New York JFK',
      destinationCode: 'JFK',
      departureTime: '04:30',
      arrivalTime: '15:45',
      status: 'Delayed',
      gate: 'C22',
      terminal: 'Terminal 3',
      aircraft: 'Airbus A330-300',
      duration: '11h 15m',
      date: 'May 3, 2026',
      delayMinutes: 45,
      statusColor: 'orange',
    ),
    'MS700': Flight(
      flightNumber: 'MS700',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'Dubai',
      destinationCode: 'DXB',
      departureTime: '16:45',
      arrivalTime: '21:00',
      status: 'Boarding',
      gate: 'D5',
      terminal: 'Terminal 2',
      aircraft: 'Airbus A320',
      duration: '3h 15m',
      date: 'Apr 27, 2026',
      statusColor: 'blue',
    ),
    'MS800': Flight(
      flightNumber: 'MS800',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'Paris CDG',
      destinationCode: 'CDG',
      departureTime: '11:00',
      arrivalTime: '14:50',
      status: 'Departed',
      gate: 'B9',
      terminal: 'Terminal 2',
      aircraft: 'Boeing 737-800',
      duration: '4h 50m',
      date: 'Apr 27, 2026',
      statusColor: 'grey',
    ),
    'MS600': Flight(
      flightNumber: 'MS600',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'Riyadh',
      destinationCode: 'RUH',
      departureTime: '09:30',
      arrivalTime: '12:45',
      status: 'On Time',
      gate: 'A3',
      terminal: 'Terminal 2',
      aircraft: 'Airbus A320',
      duration: '2h 15m',
      date: 'Apr 27, 2026',
      statusColor: 'green',
    ),
    'MS650': Flight(
      flightNumber: 'MS650',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'Jeddah',
      destinationCode: 'JED',
      departureTime: '13:15',
      arrivalTime: '16:00',
      status: 'On Time',
      gate: 'B2',
      terminal: 'Terminal 2',
      aircraft: 'Boeing 737-800',
      duration: '2h 45m',
      date: 'Apr 27, 2026',
      statusColor: 'green',
    ),
    'MS300': Flight(
      flightNumber: 'MS300',
      origin: 'Cairo',
      originCode: 'CAI',
      destination: 'Frankfurt',
      destinationCode: 'FRA',
      departureTime: '07:00',
      arrivalTime: '10:30',
      status: 'Cancelled',
      gate: '—',
      terminal: 'Terminal 2',
      aircraft: 'Airbus A330-200',
      duration: '4h 30m',
      date: 'Apr 27, 2026',
      statusColor: 'red',
    ),
  };

  static bool isTicketNumber(String input) {
    // Matches "EF 381-7612834521" or "EF381-7612834521" (case-insensitive)
    final cleaned = input.replaceAll(' ', '').toUpperCase();
    return cleaned == 'EF381-7612834521';
  }

  static Future<Flight?> lookupFlight(String code) async {
    await Future.delayed(const Duration(milliseconds: 800));
    final key = code.toUpperCase().trim();
    return _flightDatabase[key];
  }
}
